apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_HOST: bG9jYWxob3N0Cg==  # "localhost" in base64
  DB_USER: YWRtaW4K         # "admin" in base64
  DB_PASSWORD: dW5pZm9uaWMzMjEK  # "unifonic321" in base64