apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/fahim-devops/php-app-unifonic.git'
    path: eks-manifest/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: unifonic
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true